// Plain (non-"use client") module so theme-provider.tsx (client) and
// theme-script.tsx (server) can both import these — a server component
// importing a data export from a "use client" module gets an opaque client
// reference instead of the real value.
export const ALL_THEME_VARS = [
  "--brand-bark",
  "--brand-sand",
  "--brand-stone",
  "--brand-cream",
  "--primary",
  "--primary-content",
  "--sidebar",
  "--sidebar-content",
  "--sidebar-primary",
  "--sidebar-primary-content",
  "--sidebar-accent",
  "--sidebar-accent-content",
  "--sidebar-border",
  "--sidebar-ring",
  "--secondary",
  "--secondary-content",
];

export type ThemeVars = Record<string, string>;

// Each preset defines brand palette vars + aligned semantic theme tokens.
// base-100/200/300 (surface/border tiers) stay neutral across every preset —
// only primary/secondary/sidebar (and the brand-* source palette) shift.
export const LIGHT_THEME_VARS: Record<string, ThemeVars> = {
  default: {
    "--brand-bark": "#384959",
    "--brand-sand": "#88BDF2",
    "--brand-stone": "#6A89A7",
    "--brand-cream": "#BDDDFC",
    "--primary": "#384959",
    "--primary-content": "#ffffff",
    "--sidebar": "#384959",
    "--sidebar-content": "#BDDDFC",
    "--sidebar-primary": "#BDDDFC",
    "--sidebar-primary-content": "#384959",
    "--sidebar-accent": "rgba(189,221,252,0.12)",
    "--sidebar-accent-content": "#BDDDFC",
    "--sidebar-border": "rgba(136,189,242,0.2)",
    "--sidebar-ring": "#88BDF2",
    "--secondary": "#BDDDFC",
    "--secondary-content": "#384959",
  },
  ocean: {
    "--brand-bark": "#1A4A5E",
    "--brand-sand": "#4AADCA",
    "--brand-stone": "#5B8EA6",
    "--brand-cream": "#C2E8F5",
    "--primary": "#1A4A5E",
    "--primary-content": "#ffffff",
    "--sidebar": "#1A4A5E",
    "--sidebar-content": "#C2E8F5",
    "--sidebar-primary": "#C2E8F5",
    "--sidebar-primary-content": "#1A4A5E",
    "--sidebar-accent": "rgba(194,232,245,0.12)",
    "--sidebar-accent-content": "#C2E8F5",
    "--sidebar-border": "rgba(74,173,202,0.2)",
    "--sidebar-ring": "#4AADCA",
    "--secondary": "#C2E8F5",
    "--secondary-content": "#1A4A5E",
  },
  forest: {
    "--brand-bark": "#1E4D35",
    "--brand-sand": "#4AAD78",
    "--brand-stone": "#5B8E70",
    "--brand-cream": "#C2F0D8",
    "--primary": "#1E4D35",
    "--primary-content": "#ffffff",
    "--sidebar": "#1E4D35",
    "--sidebar-content": "#C2F0D8",
    "--sidebar-primary": "#C2F0D8",
    "--sidebar-primary-content": "#1E4D35",
    "--sidebar-accent": "rgba(194,240,216,0.12)",
    "--sidebar-accent-content": "#C2F0D8",
    "--sidebar-border": "rgba(74,173,120,0.2)",
    "--sidebar-ring": "#4AAD78",
    "--secondary": "#C2F0D8",
    "--secondary-content": "#1E4D35",
  },
  sunset: {
    "--brand-bark": "#5E2D1A",
    "--brand-sand": "#CA6B4A",
    "--brand-stone": "#A6745B",
    "--brand-cream": "#F5D5C2",
    "--primary": "#5E2D1A",
    "--primary-content": "#ffffff",
    "--sidebar": "#5E2D1A",
    "--sidebar-content": "#F5D5C2",
    "--sidebar-primary": "#F5D5C2",
    "--sidebar-primary-content": "#5E2D1A",
    "--sidebar-accent": "rgba(245,213,194,0.12)",
    "--sidebar-accent-content": "#F5D5C2",
    "--sidebar-border": "rgba(202,107,74,0.2)",
    "--sidebar-ring": "#CA6B4A",
    "--secondary": "#F5D5C2",
    "--secondary-content": "#5E2D1A",
  },
  indigo: {
    "--brand-bark": "#2D1E5E",
    "--brand-sand": "#6B4ACA",
    "--brand-stone": "#745BB8",
    "--brand-cream": "#D8C2F5",
    "--primary": "#2D1E5E",
    "--primary-content": "#ffffff",
    "--sidebar": "#2D1E5E",
    "--sidebar-content": "#D8C2F5",
    "--sidebar-primary": "#D8C2F5",
    "--sidebar-primary-content": "#2D1E5E",
    "--sidebar-accent": "rgba(216,194,245,0.12)",
    "--sidebar-accent-content": "#D8C2F5",
    "--sidebar-border": "rgba(107,74,202,0.2)",
    "--sidebar-ring": "#6B4ACA",
    "--secondary": "#D8C2F5",
    "--secondary-content": "#2D1E5E",
  },
  slate: {
    "--brand-bark": "#263040",
    "--brand-sand": "#6B85A0",
    "--brand-stone": "#7A8FA6",
    "--brand-cream": "#C8D8E8",
    "--primary": "#263040",
    "--primary-content": "#ffffff",
    "--sidebar": "#263040",
    "--sidebar-content": "#C8D8E8",
    "--sidebar-primary": "#C8D8E8",
    "--sidebar-primary-content": "#263040",
    "--sidebar-accent": "rgba(200,216,232,0.12)",
    "--sidebar-accent-content": "#C8D8E8",
    "--sidebar-border": "rgba(107,133,160,0.2)",
    "--sidebar-ring": "#6B85A0",
    "--secondary": "#C8D8E8",
    "--secondary-content": "#263040",
  },
};

// Dark mode: neutral 3-layer surfaces come from the `.dark` block in globals.css.
// Per preset we only recolor the *primary* tokens (primary/sidebar-primary) to
// the preset's brighter brand tone, so the dark UI stays neutral but on-brand.
export const DARK_THEME_VARS: Record<string, ThemeVars> = {
  default: {
    "--brand-bark": "#384959",
    "--brand-sand": "#88BDF2",
    "--brand-stone": "#6A89A7",
    "--brand-cream": "#BDDDFC",
    "--primary": "#88BDF2",
    "--primary-content": "#0D0F12",
    "--sidebar-primary": "#88BDF2",
    "--sidebar-primary-content": "#0D0F12",
  },
  ocean: {
    "--brand-bark": "#1A4A5E",
    "--brand-sand": "#4AADCA",
    "--brand-stone": "#5B8EA6",
    "--brand-cream": "#C2E8F5",
    "--primary": "#4AADCA",
    "--primary-content": "#0D0F12",
    "--sidebar-primary": "#4AADCA",
    "--sidebar-primary-content": "#0D0F12",
  },
  forest: {
    "--brand-bark": "#1E4D35",
    "--brand-sand": "#4AAD78",
    "--brand-stone": "#5B8E70",
    "--brand-cream": "#C2F0D8",
    "--primary": "#4AAD78",
    "--primary-content": "#0D0F12",
    "--sidebar-primary": "#4AAD78",
    "--sidebar-primary-content": "#0D0F12",
  },
  sunset: {
    "--brand-bark": "#5E2D1A",
    "--brand-sand": "#CA6B4A",
    "--brand-stone": "#A6745B",
    "--brand-cream": "#F5D5C2",
    "--primary": "#CA6B4A",
    "--primary-content": "#0D0F12",
    "--sidebar-primary": "#CA6B4A",
    "--sidebar-primary-content": "#0D0F12",
  },
  indigo: {
    "--brand-bark": "#2D1E5E",
    "--brand-sand": "#6B4ACA",
    "--brand-stone": "#745BB8",
    "--brand-cream": "#D8C2F5",
    "--primary": "#6B4ACA",
    "--primary-content": "#F0F2F5",
    "--sidebar-primary": "#6B4ACA",
    "--sidebar-primary-content": "#F0F2F5",
  },
  slate: {
    "--brand-bark": "#263040",
    "--brand-sand": "#6B85A0",
    "--brand-stone": "#7A8FA6",
    "--brand-cream": "#C8D8E8",
    "--primary": "#6B85A0",
    "--primary-content": "#0D0F12",
    "--sidebar-primary": "#6B85A0",
    "--sidebar-primary-content": "#0D0F12",
  },
};

// Path prefixes of the agent + admin portals — the only routes with dark mode
// and preset colors. theme-script.tsx applies the theme pre-paint only on
// these, so the customer portal / login stay light on a full page load.
export const THEMED_ROUTE_PREFIXES = [
  "/admin",
  "/canned-responses",
  "/dashboard",
  "/settings",
  "/tickets",
];

export const LS_THEME = "docket_theme";
export const LS_APPEARANCE = "docket_appearance";
